### ISSUE TITLE
A thank you, a formal request for comment and a caution

### ISSUE THREAD

**Issue by b9Joker108** [TomJo2000/.dotfiles#12]
Dear TomJo2000

I apologise in advance for posting this as an issue in your .dotfiles repository, but I had a significant challenge identifying an appropriate channel to initiate correspondence.

I note not only your prodigious contribution, but extensive maintenance, of a number of software projects I use daily and have so done, for a considerable number of years. For that, your dedication and sacrifice, I thank you. Your undertakings are honourable. Most of all, I love bash, zsh and Termux and its ecosystem.

Yesterday, I am ashamed to say, I got into an impassioned and protracted Termux GitHub repository flamewar with a Termux GitHub repository administrator, with administative privileges of the 'Termux' user-account, over censorship and the posting of ** significantly edited ** content generated with the assistance of three (3) GenAI LLMs, tendered with the best of intentions and in good faith. It is my considered opinion, that what I contributed prior to the flamewar, provided significant value to the 'termux-packages' repository discussion in question and the Termux community in general. I consider unfounded and ill-informed censorship dangerous, unconscionable and ill-founded and contrary to FOSS philosophy.

Is there a Termux community protocol and policy statement on censorship of open discourse on Termux public repositories? Is their a grievance process? You are directly contributing to this project and its ecosystem and the extended community and as such, bear a public responsibility to due process and probity. You are clearly a FOSS community leader. As such, I formally entreat your considered determination and response to this matter. Your opinion is greatly valued.

I await your advice.

Thanking you in anticipation
Beauford A. Stenberg

P. S. I have learnt a lot from your .zshrc and thank you for making it public. I too am currently splitting my config into modules. Your symbolic annotations legend is a mark of brilliance. You are cited in my .zshrc as a formative influence.

**Comment by TomJo2000** [comment]
Quite frankly I have tried to write a response to this a couple times over the last week and I've come to the conclusion that I'm just gonna respond to what I feel warrants a response, and I'll leave the rest unaddressed.

> I apologise in advance for posting this as an issue in your .dotfiles repository, but I had a significant challenge identifying an appropriate channel to initiate correspondence.

I appreciate that you recognize that bringing your concerns to me in the form of an issue on my dotfiles repository is unusual, but since you feel this strongly about the situation this setting will suffice.

> I am ashamed to say, I got into an impassioned and protracted Termux GitHub repository flamewar with a Termux GitHub repository administrator, with administative privileges of the 'Termux' user-account, over censorship and the posting of ** significantly edited ** content generated with the assistance of three (3) GenAI LLMs, tendered with the best of intentions and in good faith. It is my considered opinion, that what I contributed prior to the flamewar, provided significant value to the 'termux-packages' repository discussion in question and the Termux community in general.

Quite frankly the exact details of the incident are not relevant to the decision to bar you from commenting on further discussions on Termux repositories.
We took the moderating decision to bar you from further participation is discussions on the termux-packages repository after what we have perceived as repeated disruptive conduct.
We are not a government or public sector entity and are free to moderate our repositories how we see fit.

> I consider unfounded and ill-informed censorship dangerous, unconscionable and ill-founded and contrary to FOSS philosophy.

While I can appreciate the sentiment behind this concern participation in any open source project is a privilege, not a right, and it may be revoked at the discretion of the project maintainers.

> Is there a Termux community protocol and policy statement on censorship of open discourse on Termux public repositories? Is their a grievance process? You are directly contributing to this project and its ecosystem and the extended community and as such, bear a public responsibility to due process and probity. You are clearly a FOSS community leader. As such, I formally entreat your considered determination and response to this matter. Your opinion is greatly valued.

I attempt to the best of my abilities to follow the guidelines of the [Contributor Covenant](https://www.contributor-covenant.org/) Code of Conduct in my interactions as a maintainer of the Termux project.
Though this has not currently been officially adopted and our current moderation process on the project level is somewhat more informal.
Adopting a formal code of conduct is something that has been discussed previously but doesn't currently have a deadline attached.

> I note not only your prodigious contribution, but extensive maintenance, of a number of software projects I use daily and have so done, for a considerable number of years. For that, your dedication and sacrifice, I thank you. Your undertakings are honourable. Most of all, I love bash, zsh and Termux and its ecosystem.
> [...]
> P. S. I have learnt a lot from your .zshrc and thank you for making it public. I too am currently splitting my config into modules. Your symbolic annotations legend is a mark of brilliance. You are cited in my .zshrc as a formative influence.

I am glad you find my contributions helpful and you are of course free to use, study, modify and redistribute them, in full or in part, as they best suit you.
I apologize if my actions in handling this situation, or my sentiments expressed in this response came off as overly harsh.
As this is my private dotfiles repo I would prefer to close this issue.
